// SSOT barrel — Phase 001 core + Phase 002 infra + Phase 003 identity + Phase 005 auth
export * from './schemas/phase001-init';
export * from './schemas/infra-env.schema';
export * from './schemas/identity.zod';
export * from './schemas/zod-graphql-contracts';
export * from './schemas/auth-contract';
export * from './schemas/catalog.zod';
export {
  ProductSortByEnum,
  ProductFilterInputSchema,
  PredictiveSearchQuerySchema,
  FacetCountSchema,
  ProductSearchItemSchema,
  ProductSearchResponseSchema,
  PredictiveSuggestionSchema,
  sanitizeSearchQuery,
  searchCacheKey,
  predictiveCacheKey,
} from './schemas/product-search.schema';
export type {
  ProductSortBy,
  ProductFilterInput,
  PredictiveSearchQuery,
  FacetCount,
  ProductSearchItem,
  ProductSearchResponse,
  PredictiveSuggestion,
} from './schemas/product-search.schema';
export {
  StorefrontBannerSchema,
  CategoryQuickLinkSchema,
  ProductCardSchema,
  ProductDetailSchema,
  StorefrontFeedSchema,
  effectivePrice,
  discountPercent,
} from './schemas/storefront.schema';
export type {
  StorefrontBanner,
  CategoryQuickLink,
  ProductCard,
  ProductDetail,
  StorefrontFeed,
} from './schemas/storefront.schema';
export {
  CartItemTypeEnum,
  CarrierEnum,
  SmartCartItemSchema,
  HybridCartSplitSummarySchema,
  CalculateShippingInputSchema,
  AddToCartInputSchema,
  UpdateCartItemQuantityInputSchema,
  isPhysicalProduct,
  effectiveUnitPrice,
} from './schemas/cart.schema';
export type {
  CartItemType,
  Carrier,
  SmartCartItem,
  HybridCartSplitSummary,
  CalculateShippingInput,
  AddToCartInput,
  UpdateCartItemQuantityInput,
} from './schemas/cart.schema';
export {
  OrderStatusEnum as OrderStatusEnumFromOrder,
  OrderItemInputSchema,
  CreateOrderInputSchema,
  OrderItemSchema,
  OrderSchema,
  generateOrderNumber,
} from './schemas/order.schema';
export type { OrderItemInput, CreateOrderInput, OrderItem, Order } from './schemas/order.schema';
export { SlipVerificationPayloadSchema } from './schemas/sdid-contract';
export type { SlipVerificationPayload } from './schemas/sdid-contract';
export {
  PaymentStatusEnum,
  VerifySlipInputSchema,
  SlipVerificationResultSchema,
  PromptPayPayloadSchema,
  CreateOrderPayloadSchema,
  promptPayExpiry,
} from './schemas/payment.schema';
export type {
  PaymentStatus,
  VerifySlipInput,
  SlipVerificationResult,
  PromptPayPayload,
  CreateOrderPayload,
} from './schemas/payment.schema';
export {
  ContentAccessTypeEnum as ContentAccessTypeEnumFromEntitlement,
  GrantEntitlementInputSchema,
  EntitlementSchema,
} from './schemas/entitlement.schema';
export type { GrantEntitlementInput, Entitlement } from './schemas/entitlement.schema';
export {
  PromptPayStatusEnum,
  CreatePromptPayQRInputSchema,
  PromptPayQRPayloadSchema,
  PromptPayExpiryStatusSchema,
  PROMPTPAY_DEFAULT_TTL_SEC,
  PROMPTPAY_RATE_LIMIT,
  PROMPTPAY_RATE_WINDOW_SEC,
  PROMPTPAY_FRAUD_STRIKES,
  PROMPTPAY_FRAUD_FREEZE_SEC,
} from './schemas/promptpay.schema';
export type {
  PromptPayStatus,
  CreatePromptPayQRInput,
  CreatePromptPayQRRequest,
  PromptPayQRPayload,
  PromptPayExpiryStatus,
} from './schemas/promptpay.schema';
export {
  OrderStatusEnum as OrderStatusEnumFromSlip,
  PaymentStatusEnum as PaymentStatusEnumFromSlip,
  SlipVerificationInputSchema,
  EasySlipDataSchema,
  EasySlipResponseSchema,
  SlipVerificationResponseSchema,
  SLIP_TRANSREF_LOCK_SEC,
  SLIP_CLIENT_MAX_KB,
} from './schemas/slip-verification.schema';
export type {
  SlipVerificationInput,
  SlipVerificationRequest,
  EasySlipData,
  EasySlipResponse,
  SlipVerificationResponse,
} from './schemas/slip-verification.schema';
export {
  SlipVerificationRequestSchema,
  EasySlipBankDetailSchema,
  EasySlipResponseDataSchema,
  EasySlipVerifyResultSchema,
  SlipAtomicResponseSchema,
  OutboxEventTypeEnum,
  SlipRetryJobSchema,
} from './schemas/payment-slip.schema';
export type {
  SlipVerificationRequest as SlipAtomicRequest,
  EasySlipBankDetail,
  EasySlipResponseData,
  EasySlipVerifyResult,
  SlipAtomicResponse,
  OutboxEventType,
  SlipRetryJob,
} from './schemas/payment-slip.schema';
export {
  SlipPickerSourceEnum,
  SlipPickerAnalyticsEventSchema,
  SLIP_PICKER_MAX_SOURCE_BYTES,
  SLIP_PICKER_TARGET_KB,
} from './schemas/slip-picker.schema';
export type { SlipPickerSource, SlipPickerAnalyticsEvent } from './schemas/slip-picker.schema';
export {
  AssetTypeEnum,
  AssetSortEnum,
  ContentAccessTypeEnum,
  DigitalAssetSchema,
  MyLibraryQueryInputSchema,
  MyLibraryPayloadSchema,
  LIBRARY_CACHE_TTL_SEC,
  libraryCacheKey,
  libraryGateKey,
} from './schemas/library-contract';
export type { AssetType, AssetSort, DigitalAsset, MyLibraryQueryInput, MyLibraryPayload } from './schemas/library-contract';
export {
  LedgerTypeEnum,
  WalletTopupInputSchema,
  OneClickBuyInputSchema,
  WalletBalanceResponseSchema,
  WalletLedgerItemSchema,
  OneClickBuyResultSchema,
  WalletTopupResultSchema,
  WALLET_LOCK_TTL_SEC,
  WALLET_TOPUP_BONUS_RATE,
  walletLockKey,
} from './schemas/wallet-contract';
export type {
  LedgerType,
  WalletTopupInput,
  OneClickBuyInput,
  WalletBalanceResponse,
  WalletLedgerItem,
  OneClickBuyResult,
  WalletTopupResult,
} from './schemas/wallet-contract';
export {
  ReceiptDeliveryStatusEnum,
  ReceiptLineItemSchema,
  LineReceiptPayloadSchema,
  ReceiptLogSchema,
  ReceiptDownloadTicketSchema,
  FLEX_MAX_BYTES,
  RECEIPT_MAX_RETRIES,
  RECEIPT_URL_TTL_SEC,
  vatIncluded,
  receiptR2Key,
} from './schemas/line-receipt.schema';
export type {
  ReceiptDeliveryStatus,
  ReceiptLineItem,
  LineReceiptPayload,
  ReceiptLog,
  ReceiptDownloadTicket,
} from './schemas/line-receipt.schema';
export {
  LiffEnvironmentEnum,
  LiffInitPayloadSchema,
  LiffAuthHandshakeSchema,
  LiffAuthResponseSchema,
} from './schemas/liff-auth.schema';
export type {
  LiffInitPayload,
  LiffAuthHandshake,
  LiffAuthResponse,
  LiffEnvironment,
} from './schemas/liff-auth.schema';
export {
  EnvironmentTypeEnum,
  SafeAreaInsetsSchema,
  ViewportMetricsSchema,
  SyncEnvironmentPayloadSchema,
  LayoutModeEnum,
} from './schemas/environment-contract';
export type {
  EnvironmentType,
  SafeAreaInsets,
  ViewportMetrics,
  SyncEnvironmentPayload,
  LayoutMode,
} from './schemas/environment-contract';
export {
  HeaderDisplayModeEnum,
  HeaderActionIconSchema,
  DynamicHeaderPayloadSchema,
  DynamicHeaderInputSchema,
} from './schemas/header-contract';
export type {
  DynamicHeaderPayload,
  DynamicHeaderInput,
  HeaderDisplayMode,
  HeaderActionIcon,
} from './schemas/header-contract';
export {
  ServiceMessageTypeEnum,
  ServiceMessageDispatchPayloadSchema,
  DispatchStatusEnum,
  ServiceMessageDeliveryStatusSchema,
  FlexCompileInputSchema,
  FLEX_IMAGE_MAX_BYTES,
  DISPATCH_MAX_RETRIES,
  DISPATCH_BACKOFF_MS,
  DISPATCH_CIRCUIT_THRESHOLD,
} from './schemas/service-message-contract';
export type {
  ServiceMessageType,
  ServiceMessageDispatchPayload,
  DispatchStatus,
  ServiceMessageDeliveryStatus,
  FlexCompileInput,
} from './schemas/service-message-contract';
export {
  EnvironmentTypeEnum as ResolverEnvironmentEnum,
  DeepLinkTargetTypeEnum,
  ResolvedStateSchema,
  CreateShortLinkInputSchema,
  ShortCodeParamSchema,
  ResolveShortCodeResponseSchema,
  detectEnvironment as detectResolverEnvironment,
  defaultTargetPath,
  parseLiffStateToPath,
  RESOLVER_LATENCY_BUDGET_MS,
  NATIVE_HANDOFF_TIMEOUT_MS,
  RESOLVER_RATE_LIMIT_PER_MIN,
} from './schemas/resolver-contract';
export type {
  EnvironmentType as ResolverEnvironmentType,
  DeepLinkTargetType,
  ResolvedState,
  CreateShortLinkInput,
  ShortCodeParam,
  ResolveShortCodeResponse,
} from './schemas/resolver-contract';
export {
  ShareTargetTypeEnum,
  ShareStatusEnum,
  ShareContentTypeEnum,
  DynamicFlexShareInputSchema,
  FlexMessagePayloadSchema,
  RecordShareLogInputSchema,
  ShareTargetPickerResultSchema,
  GenerateFlexShareResponseSchema,
  SHARE_REWARD_POINTS,
  REFERRAL_BIND_DAYS,
  SHARE_PREVIEW_MAX_PAGE,
} from './schemas/social-share.schema';
export type {
  ShareTargetType,
  ShareStatus,
  ShareContentType,
  DynamicFlexShareInput,
  FlexMessagePayload,
  RecordShareLogInput,
  ShareTargetPickerResult,
  GenerateFlexShareResponse,
} from './schemas/social-share.schema';
export {
  NavigationStackItemSchema,
  NavigationStateSchema,
  NavigationSyncPayloadSchema,
  NavUiStateEnum,
  NavDropOffEventSchema,
  NAV_STACK_MAX_DEPTH,
  NAV_SNAPSHOT_MAX_BYTES,
  NAV_SESSION_TTL_SEC,
  NAV_DROP_OFF_CHANNEL,
  NAV_STACK_BUDGET_MB,
  navSessionKey,
  deriveNavUiState,
} from './schemas/navigation.schema';
export type {
  NavigationStackItem,
  NavigationState,
  NavigationSyncPayload,
  NavUiState,
  NavDropOffEvent,
} from './schemas/navigation.schema';
export {
  CspDispositionEnum,
  NativeCspReportSchema,
  CspReportPayloadSchema,
  AnyCspReportEnvelopeSchema,
  DomainWhitelistConfigSchema,
  HlsStreamTokenPayloadSchema,
  CspViolationRecordSchema,
  SecuritySeverityEnum,
  CSP_REPORT_PATH,
  CSP_QUEUE,
  CSP_MAX_BYTES,
  R2_CORS_MAX_AGE,
  CDN_VIDEO,
  CDN_ASSET,
  API_ORIGIN,
  LIFF_ORIGIN,
  normalizeCspReport,
  classifyCspSeverity,
  buildCspHeader,
  isOriginWhitelisted,
} from './schemas/security-csp.schema';
export type {
  CspDisposition,
  NativeCspReport,
  CspReportPayload,
  AnyCspReportEnvelope,
  DomainWhitelistConfig,
  HlsStreamTokenPayload,
  CspViolationRecord,
  SecuritySeverity,
  CspHeaderOptions,
} from './schemas/security-csp.schema';
export {
  PerformanceMetricTypeEnum,
  BundleGuardMetricSchema,
  PrefetchResourceTypeEnum,
  PrefetchRequestSchema,
  PrefetchPayloadSchema,
  TelemetryIngestSchema,
  BUNDLE_MAX_BYTES,
  BUNDLE_CHUNK_MAX_BYTES,
  PREFETCH_TTL_SEC,
  PREFETCH_DWELL_MS,
  VELOCITY_FAST_SEC_PER_PAGE,
  VELOCITY_SLOW_SEC_PER_PAGE,
  PERF_TELEMETRY_CHANNEL,
  prefetchCacheKey,
  rumToMetricType,
  velocityPrefetchCount,
} from './schemas/performance.schema';
export type {
  PerformanceMetricType,
  BundleGuardMetric,
  PrefetchResourceType,
  PrefetchRequest,
  PrefetchPayload,
  TelemetryIngest,
} from './schemas/performance.schema';
export {
  NavigationBarIconThemeEnum,
  TenantBrandingSchema,
  UpdateNavbarThemeInputSchema,
  tenantThemeKey,
  TENANT_THEME_TTL_SEC,
  THEME_ANALYTICS_CHANNEL,
  WCAG_AA_MIN_RATIO,
  relativeLuminance,
  contrastRatio,
  ensureReadableText,
  resolveIconTheme,
} from './schemas/tenant-branding.schema';
export type {
  NavigationBarIconTheme,
  TenantBranding,
  UpdateNavbarThemeInput,
} from './schemas/tenant-branding.schema';
export {
  ViewportTypeEnum,
  EbookKeepAliveStateSchema,
  VideoKeepAliveStateSchema,
  CheckoutKeepAliveStateSchema,
  KeepAliveSyncPayloadSchema,
  KeepAliveStatusEnum,
  KEEPALIVE_TTL_SEC,
  KEEPALIVE_SAVE_INTERVAL_MS,
  REHYDRATE_BUDGET_MS,
  KEEPALIVE_DB,
  KEEPALIVE_STORE,
  KEEPALIVE_CHANNEL,
  keepAliveKey,
  keepAliveRedisKey,
  pickViewportState,
} from './schemas/keep-alive-contract';
export type {
  ViewportType,
  EbookKeepAliveState,
  VideoKeepAliveState,
  CheckoutKeepAliveState,
  KeepAliveSyncPayload,
  KeepAliveStatus,
} from './schemas/keep-alive-contract';
export {
  PermissionTypeEnum,
  PermissionStatusEnum,
  DevicePlatformEnum,
  PermissionRequestPayloadSchema,
  GeolocationCoordinatesSchema,
  ReverseGeocodeResultSchema,
  PermissionAuditLogSchema,
  GEOLOCATION_TIMEOUT_MS,
  GEOCODE_CACHE_TTL_SEC,
  PERMISSION_ANALYTICS_CHANNEL,
  geocodeCacheKey,
  detectDevicePlatform,
  PERMISSION_SHEET_COPY,
  SETTINGS_PATH_COPY,
} from './schemas/permission-contract';
export type {
  PermissionType,
  PermissionStatus,
  DevicePlatform,
  PermissionRequestPayload,
  GeolocationCoordinates,
  ReverseGeocodeResult,
  PermissionAuditLog,
  PermissionSheetCopy,
} from './schemas/permission-contract';
export {
  UpdatePolicyEnum,
  AppVersionSchema,
  VersionPlatformEnum,
  VersionCheckRequestSchema,
  VersionCheckResponseSchema,
  LatestReleaseSchema,
  ClientDeviceLogSchema,
  VERSION_CACHE_TTL_SEC,
  VERSION_CACHE_PREFIX,
  UPDATE_LOOP_MAX,
  UPDATE_LOOP_KEY,
  versionCacheKey,
  compareSemver,
  evaluateUpdate,
} from './schemas/version-contract';
export type {
  UpdatePolicy,
  AppVersion,
  VersionPlatform,
  VersionCheckRequest,
  VersionCheckResponse,
  ClientDeviceLog,
  LatestRelease,
} from './schemas/version-contract';
export {
  BotPromptModeEnum,
  LineOAFriendshipStatusSchema,
  LineAuthWithOAPromptInputSchema,
  LineWebhookEventSchema,
  LineOAPublicConfigSchema,
  OA_EVENT_CHANNEL,
  OA_BOT_PROMPT_DEFAULT,
  OA_FRIEND_CACHE_TTL_MS,
  oaFriendCacheKey,
  oaAddFriendUrl,
  oaQrImageUrl,
} from './schemas/line-oa-contract';
export type {
  BotPromptMode,
  LineOAFriendshipStatus,
  LineAuthWithOAPromptInput,
  LineWebhookEvent,
  LineOAPublicConfig,
} from './schemas/line-oa-contract';
export {
  LineReviewCategoryEnum,
  LineSandboxTestResultSchema,
  LineReviewAuditSummarySchema,
  SandboxSignalsSchema,
  RunAuditInputSchema,
  REVIEW_APPROVAL_SCORE,
  AUDIT_EVENT_CHANNEL,
  SANDBOX_RAM_LIMIT_MB,
  HANDSHAKE_BUDGET_MS,
  FIRST_PAINT_BUDGET_MS,
  scoreOf,
  isApprovedForSubmission,
} from './schemas/line-review-contract';
export type {
  LineReviewCategory,
  LineSandboxTestResult,
  LineReviewAuditSummary,
  SandboxSignals,
  RunAuditInput,
} from './schemas/line-review-contract';
export {
  StorageProviderEnum,
  MediaTypeEnum,
  R2ObjectMetadataSchema,
  EbookChunkFetchRequestSchema,
  HlsQualityEnum,
  HlsStreamSignedUrlRequestSchema,
  SignedStreamUrlResponseSchema,
  R2UploadRequestSchema,
  R2_DEFAULT_BUCKET,
  R2_CHUNK_CACHE_TTL_SEC,
  HLS_TOKEN_TTL_SEC,
  R2_PREVIEW_MAX_PAGE,
  HLS_LADDER,
  chunkObjectKey,
  hlsObjectPrefix,
  chunkCacheKey,
} from './schemas/r2-storage-contract';
export type {
  StorageProvider,
  MediaType,
  R2ObjectMetadata,
  EbookChunkFetchRequest,
  HlsQuality,
  HlsStreamSignedUrlRequest,
  SignedStreamUrlResponse,
  R2UploadRequest,
} from './schemas/r2-storage-contract';
export {
  EbookChapterSchema,
  EbookDetailSchema,
  LessonQuizSchema,
  CourseLessonSchema,
  CourseSectionSchema,
  CourseDetailSchema,
  CreateEbookChapterSchema,
  CreateCourseLessonSchema,
  CurriculumQuerySchema,
  totalHoursOf,
  byLessonOrder,
  byOrderIndex,
} from './schemas/ebook-course-contract';
export type {
  EbookChapter,
  EbookDetail,
  LessonQuiz,
  CourseLesson,
  CourseSection,
  CourseDetail,
  CreateEbookChapter,
  CreateCourseLesson,
  CurriculumQuery,
} from './schemas/ebook-course-contract';
export {
  BookJobStatusEnum,
  ProcessBookJobInputSchema,
  EbookChunkMetadataSchema,
  BookPipelineStatusResponseSchema,
  PagePayloadSchema,
  SVG_PAGE_MAX_BYTES,
  PIPELINE_CHUNK_TTL_SEC,
  PIPELINE_MAX_RETRIES,
  chunkR2Path,
  progressFor,
} from './schemas/book-pipeline.zod';
export type {
  BookJobStatus,
  ProcessBookJobInput,
  EbookChunkMetadata,
  BookPipelineStatusResponse,
  PagePayload,
} from './schemas/book-pipeline.zod';
export {
  ChunkCacheKeyParamsSchema,
  RedisChunkPayloadSchema,
  CacheMetricsSchema,
  CHUNK_CACHE_TTL_SEC,
  EDGE_HIT_SLA_MS,
  EDGE_SELFHEAL_MS,
  EDGE_WARM_BUDGET_MS,
  CHUNK_WINDOW_RADIUS,
  buildChunkCacheKey,
  chunkInvalidationPattern,
  slidingWindowPages,
  chunkR2ObjectKey,
} from './schemas/chunk-cache.schema';
export type {
  ChunkCacheKeyParams,
  RedisChunkPayload,
  CacheMetrics,
} from './schemas/chunk-cache.schema';
export {
  ForensicWatermarkSchema,
  EbookChunkPayloadSchema,
  ReaderProgressPayloadSchema,
  ProgressSyncResultSchema,
  READER_CHUNK_TTL_SEC,
  READER_RAM_BUDGET_MB,
  READER_RAM_WARN_MB,
  READER_WINDOW_RADIUS,
  readerLegacyCacheKey,
  readerWindowPages,
  readerEvictedPages,
} from './schemas/reader.schema';
export type {
  ForensicWatermark,
  EbookChunkPayload,
  ReaderProgressPayload,
  ProgressSyncResult,
} from './schemas/reader.schema';
export {
  ThemeModeEnum,
  ReaderPreferenceSchema,
  BoundingBoxRectSchema,
  CreateBookmarkInputSchema,
  CreateHighlightInputSchema,
  BookmarkToggleResultSchema,
  ANNOTATION_CACHE_TTL_SEC,
  PAGE_SLIDER_DEBOUNCE_MS,
  CONTROLS_AUTOHIDE_MS,
  annotationCacheKey,
  defaultReaderPreference,
} from './schemas/reader-control-contract';
export type {
  ThemeMode,
  ReaderPreference,
  BoundingBoxRect,
  CreateBookmarkInput,
  CreateHighlightInput,
  BookmarkToggleResult,
} from './schemas/reader-control-contract';
export {
  WatermarkMotionModeEnum,
  WatermarkSeedPayloadSchema,
  ForensicVerificationPayloadSchema,
  WATERMARK_SEED_TTL_SEC,
  WATERMARK_STEGO_SIZE_PX,
  WATERMARK_OPACITY_MIN,
  WATERMARK_OPACITY_MAX,
  WATERMARK_IDLE_AFTER_MS,
  WATERMARK_ACTIVE_FPS,
  WATERMARK_IDLE_FPS,
  WATERMARK_EVENT_STREAM,
  WatermarkViolationTypeEnum,
  lissajousPosition,
  watermarkHmacMessage,
} from './schemas/watermark-contract';
export type {
  WatermarkMotionMode,
  WatermarkSeedPayload,
  ForensicVerificationPayload,
  WatermarkViolationType,
} from './schemas/watermark-contract';
export {
  VideoStatusEnum,
  VideoResolutionEnum,
  InitiateUploadSchema,
  VideoTranscodeJobPayloadSchema,
  HlsManifestStreamPayloadSchema,
  VIDEO_RENDITION_LADDER,
  VIDEO_UPLOAD_PART_BYTES,
  VIDEO_DISPATCH_BUDGET_MS,
  VIDEO_MAX_RETRIES,
  VIDEO_PROGRESS_SYNC_SEC,
  VIDEO_TOKEN_TTL_SEC,
  VIDEO_RAM_BUDGET_MB,
  rawVideoPrefix,
  rawVideoPartKey,
  hlsOutputPrefix,
  hlsMasterKey,
  hlsVariantKey,
  hlsKeyObjectKey,
  VideoWorkerEventSchema,
  VideoProgressReportSchema,
} from './schemas/video-pipeline-contract';
export type {
  VideoStatus,
  VideoResolution,
  InitiateUpload,
  VideoTranscodeJobPayload,
  HlsManifestStreamPayload,
  VideoWorkerEvent,
  VideoProgressReport,
} from './schemas/video-pipeline-contract';
export {
  TranscodeQualityEnum,
  TranscodeStatusEnum,
  VideoTranscodeJobSchema,
  HlsVariantMetadataSchema,
  HLS_SEGMENT_MAX_BYTES,
  HLS_SEGMENT_SECONDS,
  TRANSCODE_STAGE_WEIGHTS,
  TRANSCODE_POLL_MS,
  lessonHlsPrefix,
  lessonMasterKey,
  lessonVariantPlaylist,
  SubmitTranscodeJobSchema,
} from './schemas/video-transcode.contract';
export type {
  TranscodeQuality,
  TranscodeStatus,
  VideoTranscodeJob,
  HlsVariantMetadata,
  SubmitTranscodeJob,
} from './schemas/video-transcode.contract';
export {
  PlaybackSpeedEnum,
  VideoQualityEnum,
  LessonStreamPayloadSchema,
  SyncLessonProgressSchema,
  ProgressSyncResponseSchema,
  VIDEO_DROPOFF_STREAM,
  LESSON_STATE_CACHE_SEC,
  LESSON_COMPLETION_RATIO,
  isLessonCompleted,
  clampResumeSec,
} from './schemas/stream-contract';
export type {
  PlaybackSpeed,
  StreamVideoQuality,
  LessonStreamPayload,
  SyncLessonProgress,
  ProgressSyncResponse,
} from './schemas/stream-contract';
export {
  SyncProgressInputSchema,
  SyncProgressPayloadSchema,
  LessonStreamStateSchema,
  PROGRESS_SYNC_INTERVAL_MS,
  PROGRESS_FLUSH_INTERVAL_SEC,
  PROGRESS_RATE_LIMIT,
  PROGRESS_RATE_WINDOW_SEC,
  PROGRESS_COMPLETION_RATIO,
  progressBufferKey,
  heatmapKey,
  secondBucket,
  bufferCompleted,
  BeaconProgressSchema,
} from './schemas/progress-sync.schema';
export type {
  SyncProgressInput,
  SyncProgressPayload,
  LessonStreamState,
  BeaconProgress,
} from './schemas/progress-sync.schema';
export {
  QuizTypeEnum,
  QuizOptionSchema,
  InVideoQuizDetailSchema,
  SubmitQuizAnswerInputSchema,
  QuizEvaluationResultSchema,
  QuizCheckpointSchema,
  QuizAttemptEventSchema,
  sanitizeCheckpoint,
  isChoiceCorrect,
  normalizeShortAnswer,
} from './schemas/quiz-contract';
export {
  CertificateStatusEnum,
  GenerateCertificateInputSchema,
  VerifyCertificateResponseSchema,
  CertificatePayloadSchema,
  CertificateItemSchema,
  generateCertificateNo,
  buildVerifyUrl,
  buildHmacPayload,
  signCertificate,
  verifyCertificateSignature,
  certificateR2Path,
  verifyUrl,
  rateLimitKey,
} from './schemas/certificate-contract';
export type {
  CertificateStatus,
  GenerateCertificateInput,
  VerifyCertificateResponse,
  CertificatePayload,
  CertificateItem,
} from './schemas/certificate-contract';
export type {
  QuizType,
  QuizOption,
  InVideoQuizDetail,
  SubmitQuizAnswerInput,
  QuizEvaluationResult,
  QuizCheckpoint,
  QuizAttemptEvent,
} from './schemas/quiz-contract';
export {
  DrmSecurityLevelEnum,
  DrmViolationTypeEnum,
  PixelTileMatrixSchema,
  DrmSessionHandshakeSchema,
  ForensicPayloadSchema,
  DecryptChunkPayloadSchema,
  DRM_SESSION_TTL_SEC,
  DRM_TILE_SIZE,
  DRM_TILE_SIZE_FALLBACK,
  DRM_PIXEL_SCRAPE_LIMIT_PER_SEC,
  DRM_FRAME_BUDGET_MS,
  DRM_RAM_BUDGET_MB,
  drmSessionKey,
  drmPixelRateKey,
  drmViolationKey,
  drmSessionExpiry,
  isValidPermutation,
  invertPermutation,
  tileGrid,
  lsbCapacityChars,
  embedLsb,
  extractLsb,
} from './schemas/drm-contract';
export type {
  DrmSecurityLevel,
  DrmViolationType,
  PixelTileMatrix,
  DrmSessionHandshake,
  ForensicPayload,
  DecryptChunkPayload,
} from './schemas/drm-contract';
export {
  StreamTokenTypeEnum,
  HlsStreamTokenRequestSchema,
  // Phase 028 already owns `HlsStreamTokenPayloadSchema` (CSP token gate) and
  // Phase 044 owns `VIDEO_TOKEN_TTL_SEC` (=300s transcode token): alias the
  // Phase 050 short-lived (10s) variants to avoid barrel collisions.
  HlsStreamTokenPayloadSchema as VideoSecurityTokenPayloadSchema,
  VideoSegmentRequestSchema,
  AntiScrapingViolationLogSchema,
  VIDEO_RATE_WINDOW_SEC,
  VIDEO_RATE_MAX_BURST_SEGMENTS,
  VIDEO_SCRAPE_BURST_PER_SEC,
  VIDEO_SCRAPE_RISK_BAN_THRESHOLD,
  VIDEO_SCRAPE_RISK_WINDOW_SEC,
  VIDEO_SCRAPE_TEMP_BLOCK_SEC,
  VIDEO_TOKEN_TTL_SEC as VIDEO_SEGMENT_TOKEN_TTL_SEC,
  VIDEO_KEY_ROTATION_SEC,
  VIDEO_TOKEN_RENEW_SEC,
  VIDEO_PLAYER_MAX_BUFFER_SEC,
  VIDEO_PLAYER_MAX_MAX_BUFFER_SEC,
  VIDEO_429_RETRY_BASE_MS,
  videoRateLimitKey,
  videoHeartbeatKey,
  videoRiskScoreKey,
  videoRequestStreamKey,
  videoSessionKey,
  videoBackoffMs,
  isNonSequentialFetch,
} from './schemas/video-security.schema';
export type {
  StreamTokenType,
  HlsStreamTokenRequest,
  HlsStreamTokenPayload as VideoSecurityTokenPayload,
  VideoSegmentRequest,
  AntiScrapingViolationLog,
} from './schemas/video-security.schema';
export {
  PreviewContentTypeEnum,
  PreviewAccessCheckSchema,
  EbookPreviewChunkPayloadSchema,
  VideoPreviewStreamPayloadSchema,
  PaywallTriggerPayloadSchema,
  PreviewEventInputSchema,
  PREVIEW_EBOOK_DEFAULT_PAGES,
  PREVIEW_VIDEO_DEFAULT_SEC,
  PREVIEW_HLS_TOKEN_TTL_SEC,
  PREVIEW_ANALYTICS_TICK_SEC,
  PREVIEW_LIFF_RAM_BUDGET_MB,
  previewChunkKey,
  previewUsageId,
  isEbookPageAllowed,
  isVideoSecondAllowed,
  previewLimitMessage,
  remainingQuotaLabel,
} from './schemas/preview-contract';
export type {
  PreviewContentType,
  PreviewAccessCheck,
  EbookPreviewChunkPayload,
  VideoPreviewStreamPayload,
  PaywallTriggerPayload,
  PreviewEventInput,
} from './schemas/preview-contract';
export {
  AnalyticsEventTypeEnum,
  ReadTimeTrackingPayloadSchema,
  WatchTimeTrackingPayloadSchema,
  AnalyticsBatchIngestSchema,
  ANALYTICS_STREAM_KEY,
  ANALYTICS_HEARTBEAT_SEC,
  ANALYTICS_FLUSH_SEC,
  ANALYTICS_HEATMAP_SEGMENT_SEC,
  ANALYTICS_RING_CAP,
  ANALYTICS_PULSE_PER_MIN,
  ANALYTICS_DRAIN_BATCH_SEC,
  ANALYTICS_NIL_USER,
  analyticsPulseKey,
  heatmapSegmentIndex,
  completionRate,
  dropoffRate,
  averageDwell,
} from './schemas/analytics-contract';
export type {
  AnalyticsEventType,
  ReadTimeTrackingPayload,
  WatchTimeTrackingPayload,
  AnalyticsBatchIngestPayload,
} from './schemas/analytics-contract';
export {
  HlsTokenPayloadSchema,
  GenerateHlsTokenInputSchema,
  HlsStreamResponseSchema,
  HLS_SEGMENT_TOKEN_TTL_SEC,
  HLS_TOKEN_ROTATE_SEC,
  HLS_EDGE_VERIFY_BUDGET_MS,
  HLS_MINT_BUDGET_MS,
  HLS_MAX_BUFFER_SEGMENTS,
  HLS_CLOCK_SKEW_SEC,
  HLS_TOKEN_MISSING,
  HLS_TOKEN_EXPIRED,
  HLS_TOKEN_INVALID,
  HLS_SECURITY_INCIDENT,
  hlsTokenBody,
  parseHlsTokenBody,
  isHlsTokenExpired,
  hlsSignedSegmentUrl,
} from './schemas/hls-stream-contract';
export type {
  HlsTokenPayload,
  GenerateHlsTokenInput,
  HlsStreamResponse,
  ParsedHlsToken,
} from './schemas/hls-stream-contract';
export {
  SyncLessonProgressInputSchema,
  RESUME_MIN_SEC,
  RESUME_MAX_COMPLETION_RATIO,
  RESUME_TOAST_AUTO_DISMISS_SEC,
  RESUME_TOAST_RENDER_BUDGET_MS,
  RESUME_SYNC_EVERY_SEC,
  shouldShowResumeToast,
  formatResumeMMSS,
} from './schemas/zod-stream';
export type { SyncLessonProgressInput } from './schemas/zod-stream';
export {
  SyncContentTypeEnum,
  EbookProgressSyncSchema,
  VideoProgressSyncSchema,
  SyncBroadcastPayloadSchema,
  ForceSyncInputSchema,
  SyncProgressPayloadGqlSchema,
  SYNC_NAMESPACE,
  SYNC_FANOUT_BUDGET_MS,
  SYNC_CLIENT_THROTTLE_MS,
  SYNC_WRITEBACK_SEC,
  SYNC_WIRE_MAX_BYTES,
  SYNC_TICKET_TTL_SEC,
  SYNC_CHANNEL_PREFIX,
  syncRoomKey,
  syncRoomChannel,
  ebookProgressCacheKey,
  videoProgressCacheKey,
  syncQueueName,
  isSyncPayloadWithinBudget,
  lastWriteWins,
} from './schemas/progress-sync-contract';
export type {
  SyncContentType,
  EbookProgressSync,
  VideoProgressSync,
  SyncBroadcastPayload,
  ForceSyncInput,
  SyncProgressPayloadGql,
} from './schemas/progress-sync-contract';
export {
  NetworkQualityTierEnum,
  ClientNetworkTelemetrySchema,
  LowBandwidthChunkRequestSchema,
  LowBandwidthChunkResponseSchema,
  LOW_NET_FIRST_FRAME_MS,
  LOW_NET_NEXT_PAGE_MS,
  LOW_NET_RAM_CAP_MB,
  LOW_NET_BROTLI_Q_SLOW,
  LOW_NET_BROTLI_Q_FAST,
  LOW_NET_CHUNK_CACHE_TTL_SEC,
  LOW_NET_RTT_SLOW_MS,
  LOW_NET_DOWNLINK_SLOW_MBPS,
  prefetchWindow,
  tierFromEffectiveType,
  brotliQualityFor,
  isLowBandwidthTier,
  TIER_BITRATE_BUDGET_KBPS,
  filterVariantsByBudget,
} from './schemas/low-bandwidth-contract';
export type {
  NetworkQualityTier,
  ClientNetworkTelemetry,
  LowBandwidthChunkRequest,
  LowBandwidthChunkResponse,
  HlsLadderVariant,
} from './schemas/low-bandwidth-contract';
export {
  RuntimeEnvironmentEnum,
  ViewportCapabilitiesSchema,
  ViewportStateSyncSchema,
  ViewportStateSyncInputSchema,
  WatermarkConfigSchema,
  ViewportConfigPayloadSchema,
  VIEWPORT_LIFF_RAM_MB,
  VIEWPORT_WEB_RAM_MB,
  VIEWPORT_DESKTOP_BREAKPOINT_PX,
  VIEWPORT_WATERMARK_REFRESH_SEC,
  VIEWPORT_SESSION_TTL_SEC,
  VIEWPORT_LIFF_FALLBACK_MS,
  VIEWPORT_PROGRESS_SYNC_BUDGET_MS,
  detectRuntimeEnvironment,
  ramBudgetFor,
  viewportSlidingWindowPages,
  viewportSessionKey,
  watermarkTextFor,
  isLiffEnvironment,
} from './schemas/viewport-contract';
export type {
  RuntimeEnvironment,
  ViewportCapabilities,
  ViewportStateSync,
  ViewportStateSyncInput,
  WatermarkConfig,
  ViewportConfigPayload,
} from './schemas/viewport-contract';
export {
  ThumbnailCueSchema,
  VideoSpriteManifestSchema,
  VideoScrubbingPayloadSchema,
  ScrubbingManifestInputSchema,
  SCRUB_VTT_MAX_KB,
  SCRUB_SPRITE_MAX_KB,
  SCRUB_SPRITE_CACHE_LIMIT,
  SCRUB_LIFF_RAM_MB,
  SCRUB_RENDER_BUDGET_MS,
  SCRUB_MANIFEST_TTL_SEC,
  SCRUB_TILE_W,
  SCRUB_TILE_H,
  SCRUB_COLS,
  SCRUB_INTERVAL_SEC,
  SCRUB_TILES_PER_SHEET,
  SCRUB_MANIFEST_CACHE_KEY_PREFIX,
  SCRUB_ANALYTICS_STREAM_KEY,
  scrubManifestCacheKey,
  cueCoordsForFrame,
  totalTilesFor,
  cueForTime,
  toVttTimestamp,
  formatScrubTime,
} from './schemas/scrubbing-vtt.schema';
export type {
  ThumbnailCue,
  VideoSpriteManifest,
  VideoScrubbingPayload,
  ScrubbingManifestInput,
} from './schemas/scrubbing-vtt.schema';
export {
  InputDeviceEnum,
  GestureTypeEnum,
  NavigationActionEnum,
  NavigationEventPayloadSchema,
  UserReaderPreferenceSchema,
  NAV_TAP_LEFT_EDGE,
  NAV_TAP_RIGHT_EDGE,
  NAV_SWIPE_MIN_DX_PX,
  NAV_SWIPE_MIN_VELOCITY_PX_MS,
  NAV_SWIPE_MAX_DURATION_MS,
  NAV_SWIPE_AXIS_RATIO,
  NAV_TAP_MAX_DELTA_PX,
  NAV_TAP_MAX_DURATION_MS,
  NAV_KEY_THROTTLE_MS,
  NAV_FRAME_BUDGET_MS,
  NAV_ACCIDENTAL_TAP_MS,
  NAV_EVENT_STREAM_KEY,
  tapZoneFor,
  swipeActionFor,
  isTap,
  keyIntentFor,
  isTypingTarget,
  clampPage,
  isAccidentalFlip,
} from './schemas/navigation-event-contract';
export type {
  InputDevice,
  GestureType,
  NavigationAction,
  NavigationEventPayload,
  UserReaderPreference as ReaderNavigationPreference,
  UserReaderPreference,
  TapZone,
  SwipeSample,
  TapSample,
  KeyNavIntent,
} from './schemas/navigation-event-contract';
export {
  DprLevelEnum,
  ViewportMatrixSchema,
  CanvasResolutionConfigSchema,
  EbookMultiResChunkPayloadSchema,
  SCALER_DPR_CAP,
  SCALER_DPR_DEVICE_MAX,
  SCALER_ADJACENT_DPR,
  SCALER_EDGE_TTL_SEC,
  SCALER_MAX_LIVE_CANVASES,
  SCALER_LIFF_RAM_MB,
  SCALER_WINDOW_RAM_REF_MB,
  SCALER_FRAME_BUDGET_MS,
  SCALER_AI_FPS_FLOOR,
  SCALER_AI_SLOW_PAGES,
  SCALER_AI_SPIKE_MB,
  SCALER_WATERMARK_OPACITY,
  SCALER_BASE_WIDTH_PX,
  SCALER_BASE_HEIGHT_PX,
  SCALER_BYTES_PER_PX,
  SCALER_RENDER_EVENT_STREAM_KEY,
  retinaCacheKey,
  targetDprFor,
  dprVariantFor,
  canvasMemoryMb,
  viewportMatrixFor,
  slidingWindowRamMb,
  adaptiveDownscale,
  scalerTenantVars,
} from './schemas/canvas-scaler.schema';
export type {
  DprLevel,
  ViewportMatrix,
  CanvasResolutionConfig,
  EbookMultiResChunkPayload,
} from './schemas/canvas-scaler.schema';
export {
  DrmShuffleAlgorithmEnum,
  ShufflingMatrixSeedSchema,
  EncryptedDrmChunkPayloadSchema,
  DRM_SEED_MIN_LEN,
  DRM_GRID_MIN,
  DRM_GRID_MAX,
  DRM_GRID_DEFAULT,
  DRM_SESSION_TTL_MIN,
  DRM_BLOB_URL_TTL_SEC,
  DRM_VIOLATION_BUDGET_MS,
  DRM_DESHUFFLE_BUDGET_MS,
  DRM_LIFF_RAM_MB,
  DRM_SESSION_CACHE_PREFIX,
  DRM_VIOLATION_STREAM_KEY,
  drmSessionCacheKey,
  lcgNext,
  permutationFromSeed,
  tileRects,
  isBijection,
} from './schemas/drm-shuffling.schema';
// NOTE Phase 061: invertPermutation intentionally NOT re-exported here —
// Phase 049 drm-contract.ts already owns that barrel name (Zero Redundant
// Code); the 061 twin stays importable via the direct schema path.
export { invertPermutation as invertDrmShufflePermutation } from './schemas/drm-shuffling.schema';
export type {
  DrmShuffleAlgorithm,
  ShufflingMatrixSeed,
  EncryptedDrmChunkPayload,
} from './schemas/drm-shuffling.schema';
